version: "3.8"

x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: ${FLUENT_BIT_ADDRESS}:24224

services:
  post_service:
    image: post_service
    container_name: post_service
    build:
      context: .
      dockerfile: ./post_service/Dockerfile
    restart: on-failure
    environment:
      POST_DB_HOST: ${POST_DB_HOST}
      POST_DB_PORT: ${POST_DB_PORT}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      JAEGER_SERVICE_NAME: post_service
      JAEGER_AGENT_HOST: ${JAEGER_HOST}
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: ${JAEGER_HOST}:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    depends_on:
      - post_db
    logging: *fluent-bit
    networks:
      - network

  job_service:
    image: job_service
    container_name: job_service
    build:
      context: .
      dockerfile: ./job_service/Dockerfile
    restart: on-failure
    environment:
      JOB_DB_HOST: ${JOB_DB_HOST}
      JOB_DB_PORT: ${JOB_DB_PORT}
      JOB_SERVICE_PORT: ${JOB_SERVICE_PORT}
      JAEGER_SERVICE_NAME: post_service
      JAEGER_AGENT_HOST: ${JAEGER_HOST}
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: ${JAEGER_HOST}:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    depends_on:
      - job_db
    logging: *fluent-bit
    networks:
      - network

  message_service:
    image: message_service
    container_name: message_service
    build:
      context: .
      dockerfile: ./message_service/Dockerfile
    restart: on-failure
    environment:
      MESSAGE_DB_HOST: ${MESSAGE_DB_HOST}
      MESSAGE_DB_PORT: ${MESSAGE_DB_PORT}
      MESSAGE_SERVICE_PORT: ${MESSAGE_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      CREATE_MESSAGE_COMMAND_SUBJECT: ${CREATE_MESSAGE_COMMAND_SUBJECT}
      CREATE_MESSAGE_REPLY_SUBJECT: ${CREATE_MESSAGE_REPLY_SUBJECT}
      JAEGER_SERVICE_NAME: post_service
      JAEGER_AGENT_HOST: ${JAEGER_HOST}
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: ${JAEGER_HOST}:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    depends_on:
      - message_db
    logging: *fluent-bit
    networks:
      - network
  
  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: on-failure
    environment:
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      CREATE_MESSAGE_COMMAND_SUBJECT: ${CREATE_MESSAGE_COMMAND_SUBJECT}
      CREATE_MESSAGE_REPLY_SUBJECT: ${CREATE_MESSAGE_REPLY_SUBJECT}
      JAEGER_SERVICE_NAME: post_service
      JAEGER_AGENT_HOST: ${JAEGER_HOST}
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: ${JAEGER_HOST}:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    depends_on:
      - user_db
    logging: *fluent-bit
    networks:
      - network

  follow_service:
    image: follow_service
    container_name: follow_service
    build:
      context: .
      dockerfile: ./follow_service/Dockerfile
    restart: on-failure
    environment:
      FOLLOW_SERVICE_PORT:   ${FOLLOW_SERVICE_PORT}
      FOLLOW_DATABASE:       ${FOLLOW_DATABASE}
      FOLLOW_DB_HOST:        ${FOLLOW_DB_HOST}
      FOLLOW_DB_PORT:        ${FOLLOW_DB_PORT}
      FOLLOW_DB_USERNAME:    ${FOLLOW_DB_USERNAME}
      FOLLOW_DB_PASSWORD:    ${FOLLOW_DB_PASSWORD}
      DB_NEO4J_VERSION:      ${DB_NEO4J_VERSION}
      USER_SERVICE_HOST:     ${USER_SERVICE_HOST}
      USER_SERVICE_PORT:     ${USER_SERVICE_PORT}
      JAEGER_SERVICE_NAME: post_service
      JAEGER_AGENT_HOST: ${JAEGER_HOST}
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: ${JAEGER_HOST}:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      
    depends_on:
      - follow_db
    logging: *fluent-bit
    networks:
      - network

  recommendation_service:
    image: recommendation_service
    container_name: recommendation_service
    build:
      context: .
      dockerfile: ./recommendation_service/Dockerfile
    restart: on-failure
    environment:
      RECOMMENDATION_SERVICE_PORT:   ${RECOMMENDATION_SERVICE_PORT}
      RECOMMENDATION_DATABASE:       ${RECOMMENDATION_DATABASE}
      RECOMMENDATION_DB_HOST:        ${RECOMMENDATION_DB_HOST}
      RECOMMENDATION_DB_PORT:        ${RECOMMENDATION_DB_PORT}
      RECOMMENDATION_DB_USERNAME:    ${RECOMMENDATION_DB_USERNAME}
      RECOMMENDATION_DB_PASSWORD:    ${RECOMMENDATION_DB_PASSWORD}
      DB_NEO4J_VERSION:      ${DB_NEO4J_VERSION}
      JAEGER_SERVICE_NAME: post_service
      JAEGER_AGENT_HOST: ${JAEGER_HOST}
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: ${JAEGER_HOST}:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      
    depends_on:
      - recommendation_db
    logging: *fluent-bit
    networks:
      - network

  follow_db:
    image: neo4j
    container_name: follow_db
    restart: on-failure
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    logging: *fluent-bit
    networks:
      - network


  recommendation_db:
    image: neo4j
    container_name: recommendation_db
    restart: on-failure
    environment:
      NEO4J_AUTH: none
    ports:
      - 11005:7474
      - 11003:7687
    logging: *fluent-bit
    networks:
      - network

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      POST_SERVICE_HOST: ${POST_SERVICE_HOST}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      JOB_SERVICE_HOST: ${JOB_SERVICE_HOST}
      JOB_SERVICE_PORT: ${JOB_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      FOLLOW_SERVICE_HOST: ${FOLLOW_SERVICE_HOST}
      FOLLOW_SERVICE_PORT: ${FOLLOW_SERVICE_PORT}
      MESSAGE_SERVICE_HOST: ${MESSAGE_SERVICE_HOST}
      MESSAGE_SERVICE_PORT: ${MESSAGE_SERVICE_PORT}
      JAEGER_AGENT_HOST: ${JAEGER_HOST}
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: ${JAEGER_HOST}:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      RECOMMENDATION_SERVICE_HOST: ${RECOMMENDATION_SERVICE_HOST}
      RECOMMENDATION_SERVICE_PORT: ${RECOMMENDATION_SERVICE_PORT}
    logging: *fluent-bit
    networks:
      - network    

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: ./AgentService/src/main/docker/Dockerfile
    container_name: agent-app
    depends_on:
      - agent
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://agent:5432/agent
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  agent:
    image: 'postgres:13.1-alpine'
    container_name: agent
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=agent
    logging: *fluent-bit

  post_db:
    image: mongo
    container_name: post_db
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - network

  message_db:
    image: mongo
    container_name: message_db
    restart: on-failure
    #ports:
     # - 27018:27017
    networks:
      - network 

  job_db:
    image: mongo
    container_name: job_db
    restart: on-failure
    #ports:
     # - 27018:27017
    networks:
      - network

  user_db:
    image: mongo
    container_name: user_db
    restart: on-failure
    #ports:
     # - 27018:27017
    networks:
      - network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://post_db:27017
    networks:
      - network
    volumes:
      - ./mongo_post_db:/data/db

  mongo-express_message:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://message_db:27017
    networks:
      - network
    volumes:
      - ./mongo_message_db:/data/db

  mongo-express_job:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://job_db:27017
    networks:
      - network
    volumes:
      - ./mongo_job_db:/data/db

  mongo-express_user:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://user_db:27017
    networks:
      - network
    volumes:
      - ./mongo_user_db:/data/db

  nats:
    image: nats
    container_name: nats
    restart: on-failure
    networks:
      - network

  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - network

  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      ENABLE_METRICS: "true"
    networks:
      - network

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./monitoring/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
    networks:
      - network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus:/var/lib/prometheus
    networks:
      - network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - network

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8087:8087"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - network

networks:
  network:
    driver: bridge
  
volumes:
   mongo_post_db:
   mongo_job_db:
   mongo_user_db:
   mongo_message_db:
   grafana:
    name: grafana
   prometheus:
    name: prometheus