version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    working_directory: ~/XWS-Projekat-Backend/AgentService
    steps:
      - checkout
      - when:
          condition:
            equal: [ security, << pipeline.git.branch >> ]
          steps:
            - run: echo "I am on security"
            - run:
                name: Analyze on SonarCloud
                command: mvn verify sonar:sonar -Dsonar.projectKey=dunjagojkovic_XWS-Projekat-Backend

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud